FROM python:3.9-alpine3.14

RUN apk update &&\
    apk add python3-dev mariadb-dev mariadb-connector-c-dev build-base libffi-dev
WORKDIR /app
COPY requirements.txt ./
RUN python -m pip install --user --upgrade pip &&\
    pip install -r requirements.txt &&\
    apk add mariadb-client
