# Generated by Django 3.2.8 on 2021-10-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('delete_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
